# Generated by Django 5.0.2 on 2024-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_loginform'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginform',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
